version: '3.8'

services:
  edgegate:
    image: ghcr.io/reddts/edgegate-core:latest
    network_mode: host
    environment:
      CONFIG: "https://github.com/reddts/edgegate/raw/refs/heads/main/test.configs/warp"
    volumes:
      - ./edgegate.json:/degegate/edgegate.json
    command: ["/degegate/edgegate.sh"]
